### ISSUE TITLE
How to change Fahrenheit to Celsius ?

### ISSUE THREAD

**Issue by Kirachiu** [SaberAkiyama/SAWeatherCast#31]

**Comment by Kirachiu** [comment]
[Variables]

Page=Info
PageLine=80

TypeFace=Roboto
ColorText=White
ColorCode=255,255,255

LangName=English
LangCurrent=English (US)
**TempUnit=C**
WindUnit=Mph
WindUnitShort=Mph
VisibilityUnit=Mile
VisibilityUnitShort=Mi
PressureUnit=Inches
PressureUnitShort=In

I have tried to change this TempUnit to C or Celsius.

**Comment by SaberAkiyama** [comment]
Right click on the current skin, hover "Custom skin menu" and click "Open Settings panel".

In Settings, click "Language" page. If you want Celsius, click "English (World)" and click "Apply Changes" to refresh the weather skin.

**Comment by SaberAkiyama** [comment]
> [Variables]
> 
> Page=Info
> PageLine=80
> 
> TypeFace=Roboto
> ColorText=White
> ColorCode=255,255,255
> 
> LangName=English
> LangCurrent=English (US)
> **TempUnit=C**
> WindUnit=Mph
> WindUnitShort=Mph
> VisibilityUnit=Mile
> VisibilityUnitShort=Mi
> PressureUnit=Inches
> PressureUnitShort=In
> 
> I have tried to change this TempUnit to C or Celsius.

Right click on the current skin, hover "Custom skin menu" and click "Open Settings panel".

In Settings, click "Language" page. If you want Celsius, click "English (World)" and click "Apply Changes" to refresh the weather skin.

**Comment by Kirachiu** [comment]
All fixed, Thank you!
