### ISSUE TITLE
No data for all 4 current tabs (.ini), while others are all normal [Bug: Current]

### ISSUE THREAD

**Issue by glloyd0314** [SaberAkiyama/SAWeatherCast#32]
As said in title, all 4 current tabs (.ini) do not any data while others are all normal. It starts from today and I have not changed any setting of both Rainmeter and the skin. Pretty strange.
Here is the screenshot. Left is Seven Day.ini and right is Current.ini.

![](https://pic.imgdb.cn/item/62b9dbb41d64b07066aca05b.png)

 - OS: Windows 10 Pro 21H2 19044.1766
 - Rainmeter version: 4.5.13.3632 (installed by scoop)

**Comment by glloyd0314** [comment]
> Mine is okay at night time. Same as in day time. You didn't check on log.

Thank you for your screenshot showing it could work actually then it must be some problems on my side. The error log goes as:

```
NOTE (21:16:33.366) SA Weather Cast\Current\Current.ini: Refreshing skin
NOTE (21:16:33.432) SA Weather Cast\Current\Current.ini: Connecting...
NOTE (21:16:33.432) SA Weather Cast\Current\Current.ini: Retrieving Current...
NOTE (21:16:38.560) SA Weather Cast\Current\Current.ini: Weather Daily Retrieved.
ERRO (21:16:39.446) SA Weather Cast\Current\Current.ini - [MeasureCurrentSunrise12H]: Invalid TimeStampFormat: %H:%S
ERRO (21:16:39.446) SA Weather Cast\Current\Current.ini - [MeasureCurrentSunset12H]: Invalid TimeStampFormat: %H:%S
ERRO (21:16:39.447) SA Weather Cast\Current\Current.ini - [MeasureCurrentValidTime12H]: Invalid TimeStampFormat: %H:%S
```

I am wondering what problem could it be...

**Comment by SaberAkiyama** [comment]
> > Mine is okay at night time. Same as in day time. You didn't check on log.
> 
> Thank you for your screenshot showing it could work actually then it must be some problems on my side. The error log goes as:
> 
> ```
> NOTE (21:16:33.366) SA Weather Cast\Current\Current.ini: Refreshing skin
> NOTE (21:16:33.432) SA Weather Cast\Current\Current.ini: Connecting...
> NOTE (21:16:33.432) SA Weather Cast\Current\Current.ini: Retrieving Current...
> NOTE (21:16:38.560) SA Weather Cast\Current\Current.ini: Weather Daily Retrieved.
> ERRO (21:16:39.446) SA Weather Cast\Current\Current.ini - [MeasureCurrentSunrise12H]: Invalid TimeStampFormat: %H:%S
> ERRO (21:16:39.446) SA Weather Cast\Current\Current.ini - [MeasureCurrentSunset12H]: Invalid TimeStampFormat: %H:%S
> ERRO (21:16:39.447) SA Weather Cast\Current\Current.ini - [MeasureCurrentValidTime12H]: Invalid TimeStampFormat: %H:%S
> ```
> 
> I am wondering what problem could it be...

Strange. What is your location?

**Comment by SaberAkiyama** [comment]
This is Tokyo, Japan
![Screenshot 2022-06-28 213933](https://user-images.githubusercontent.com/48464326/176193482-305d39d2-73f1-473c-ae05-d4dd25a139b7.png)

This is Beijing, PRC
![Screenshot 2022-06-28 214050](https://user-images.githubusercontent.com/48464326/176193589-47e663bf-3f9c-4347-b7c2-84c6268ef500.png)

And this is Singapore
![Screenshot 2022-06-28 214024](https://user-images.githubusercontent.com/48464326/176193659-cf1052af-ba56-4023-833a-ef6c1fe1edad.png)

Anything is looks normal.

**Comment by SaberAkiyama** [comment]
Try using a long URL code rather than a short one

**Comment by glloyd0314** [comment]
> Try using a long URL code rather than a short one

Aww it works! 
For Beijing, PRC, now I use `71ca347e2948ee9490525aa5433fa91da6973ae51ea0f765fbe8e85b9f16c5df` from [the whole url from weather.com](https://weather.com/zh-CN/weather/today/l/71ca347e2948ee9490525aa5433fa91da6973ae51ea0f765fbe8e85b9f16c5df) and it shows normally.
![](https://user-images.githubusercontent.com/65362403/176198745-912ab38e-d3f9-49c9-8c24-1a7850318bd2.png)
Thank you so much for your help!

**Comment by SaberAkiyama** [comment]
You're welcome
