### ISSUE TITLE
[Bug: Forecast] Seven Day Skin Not Working

### ISSUE THREAD

**Issue by Trevor-Rosario** [SaberAkiyama/SAWeatherCast#35]
**Describe the bug**
The Seven-day forecast skin worked for 2 days before it started remaining stuck saving "Retrieving". Current and Hourly work perfectly fine, this appears only to be the case with the Seven-Day Skin.  I have attempted a fresh install only for the same problem to occur.

**Expected behavior**
Rainmeter starts and both current and seven-day forecasts are displayed

**Screenshots**
![Screenshot 2023-04-23 161313](https://user-images.githubusercontent.com/44759183/233863414-547dfdd4-6966-426a-9bfe-e64cf653431f.png)

**Desktop:**
 - OS: Windows 10 22H2
 - Rainmeter version: v4.5.17.3700

**Comment by SaberAkiyama** [comment]
Yeah, it was Daily forecast skin issues. Because TWC has been updated the JSON scripts.

**Comment by Trevor-Rosario** [comment]
Do you have any idea how to fix it? I am unfamiliar with this and would hate to mess something up by attempting my own fixes first.

**Comment by SaberAkiyama** [comment]
Mate, you didn't read on Reddit post?

https://www.reddit.com/r/Rainmeter/comments/12y7l24/sa_weather_cast_information_update/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by Trevor-Rosario** [comment]
I had not seen that post actually. Thanks for linking it for me!
